### ISSUE TITLE
Add support for loading custom graph

### ISSUE THREAD

**Issue by dibyadas** [yulonglong/VisuAlgo-List#1]
By using the `loadGraph()` we can have an input to let user enter their custom graph instead of redrawing everywhere. Also, currently the weights can't changed.

**Comment by yulonglong** [comment]
This is an old version of VisuAlgo List.

Please visit the updated and official website https://visualgo.net/ to get the latest features and support.
Any suggestion/feedback can be done through the project owner, Dr Steven Halim (stevenhalim@gmail.com).
